---
tag: myappname
user: deploy
group: deploy
rackup: config.ru
pid: tmp/thin.pid
log: log/thin.log
port: 5200
timeout: 30
max_conns: 1024
max_persistent_conns: 512
environment: production
chdir: /var/www/myappdirectory
servers: 1
daemonize: true
address: 0.0.0.0
require: []
